### ISSUE TITLE
Fail build SDL

### ISSUE THREAD

**Issue by sl1pkn07** [astiob/mplayer2#3]
Hi

i tried to build the  `all` branch with ffmpeg 2.3, but fails in:

```
CC      libvo/gl_common.o
libvo/gl_common.c: In function 'setGlWindow_sdl':
libvo/gl_common.c:2477:16: error: 'SET_WINDOW_FAILED' undeclared (first use in this function)
 2477 |         return SET_WINDOW_FAILED;
      |                ^~~~~~~~~~~~~~~~~
libvo/gl_common.c:2477:16: note: each undeclared identifier is reported only once for each function it appears in
libvo/gl_common.c:2480:12: error: 'SET_WINDOW_OK' undeclared (first use in this function)
 2480 |     return SET_WINDOW_OK;
      |            ^~~~~~~~~~~~~
libvo/gl_common.c: In function 'mpgl_init':
libvo/gl_common.c:2610:14: error: 'MPGLContext' has no member named 'create_window'; did you mean 'create_window_old'?
 2610 |         ctx->create_window = create_window_sdl;
      |              ^~~~~~~~~~~~~
      |              create_window_old
libvo/gl_common.c:2611:12: error: 'MPGLContext' has no member named 'setGlWindow'
 2611 |         ctx->setGlWindow = setGlWindow_sdl;
      |            ^~
make[1]: *** [Makefile:537: libvo/gl_common.o] Error 1
make[1]: Leaving directory '/tmp/makepkg/mplayer2-build-git/src/mplayer2-build/mplayer'
make: *** [Makefile:3: mplayer] Error 2
```

any plans to, at least, build with ffmpeg 2.3.6? (if can do more actual like 2.8.22 (release 5 moth ago) would be super!)

i want to try if this piece of the story still can do heartbeat outside audio files (build with libav fails in play videos)

greetings

**Comment by sl1pkn07** [comment]
seems something about it is removed in https://github.com/astiob/mplayer2/commit/266ff87724a78b7206f59ccbe47e5d3ff209d7f1

greetings

**Comment by astiob** [comment]
Looks like SDL code is broken, oops. Try adding `--disable-sdl` to your `./configure` call.

**Comment by sl1pkn07** [comment]
yep. build fine with `--disable-sdl`. also build ok with ffmpeg 2.8.22. but i cant get any video output, tested with GL, GL3, vdpau, xv and x11

all videos tested got something similar output

```
LC_ALL=C mplayer \[AX\]\ Kono\ Minikuku\ mo\ Utsukushii\ Sekai\ -\ 01\ \[71574CDB\].avi -v
Reading config file /etc/mplayer/mplayer.conf
get_path('') -> '/home/sl1pkn07/.mplayer/'
get_path('config') -> '/home/sl1pkn07/.mplayer/config'
Reading config file /home/sl1pkn07/.mplayer/config
MPlayer2 UNKNOWN (C) 2000-2012 MPlayer Team
CPU vendor name: GenuineIntel  max cpuid level: 20
CPU: Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (Family: 6, Model: 79, Stepping: 1)
extended cpuid-level: 8
extended cache-info: 16801856
Detected cache-line size is 64 bytes
CPUflags:  MMX: 1 MMX2: 1 3DNow: 0 3DNowExt: 0 SSE: 1 SSE2: 1 SSSE3: 1
Compiled for x86 CPU with extensions: MMX MMX2 SSE SSE2 SSSE3 CMOV
Compiled against libavutil version 54.31.100
Compiled against libavcodec version 56.60.100
Compiled against libavformat version 56.40.101
Compiled against libswscale version 3.1.101
get_path('codecs.conf') -> '/home/sl1pkn07/.mplayer/codecs.conf'
No optional codecs config file: /home/sl1pkn07/.mplayer/codecs.conf
Reading codec config file: /etc/mplayer/codecs.conf
[file] File size is 96688 bytes
STREAM: [file] /etc/mplayer/codecs.conf
STREAM: Description: File
STREAM: Author: Albeu
STREAM: Comment: based on the code from ??? (probably Arpi)
163 audio & 363 video codecs
Configuration: --extra-cflags=-I/tmp/makepkg/mplayer2-build-git/src/mplayer2-build/build_libs/include --extra-ldflags=-L/tmp/makepkg/mplayer2-build-git/src/mplayer2-build/build_libs/lib --confdir=/etc/mplayer --enable-translation --language=all --prefix=/usr --enable-joystick --enable-gif --disable-sdl
CommandLine: '[AX] Kono Minikuku mo Utsukushii Sekai - 01 [71574CDB].avi' '-v'
get_path('fonts') -> '/home/sl1pkn07/.mplayer/fonts'
Using MMX (with tiny bit MMX2) Optimized OnScreenDisplay
get_path('fonts') -> '/home/sl1pkn07/.mplayer/fonts'
[ass] Raster: FreeType 2.13.2
[ass] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 8.4.0 (COMPLEX)
[ass] Initialized
get_path('fonts') -> '/home/sl1pkn07/.mplayer/fonts'
get_path('subfont.ttf') -> '/home/sl1pkn07/.mplayer/subfont.ttf'
[ass] Updating font cache
Using nanosleep() timing
get_path('input.conf') -> '/home/sl1pkn07/.mplayer/input.conf'
Cannot open file '/home/sl1pkn07/.mplayer/input.conf': No such file or directory
Failed to open /home/sl1pkn07/.mplayer/input.conf.
Can't open input config file /home/sl1pkn07/.mplayer/input.conf.
[file] File size is 5917 bytes
STREAM: [file] /etc/mplayer/input.conf
STREAM: Description: File
STREAM: Author: Albeu
STREAM: Comment: based on the code from ??? (probably Arpi)
Parsing input config file /etc/mplayer/input.conf
Input config file /etc/mplayer/input.conf parsed: 132 binds
Opening joystick device /dev/input/js0
Can't open joystick device /dev/input/js0: No such file or directory
Can't init input joystick
Setting up LIRC support...
Failed to open LIRC support. You will not be able to use your remote control.
get_path('[AX] Kono Minikuku mo Utsukushii Sekai - 01 [71574CDB].avi.conf') -> '/home/sl1pkn07/.mplayer/[AX] Kono Minikuku mo Utsukushii Sekai - 01 [71574CDB].avi.conf'

Playing [AX] Kono Minikuku mo Utsukushii Sekai - 01 [71574CDB].avi.
get_path('sub/') -> '/home/sl1pkn07/.mplayer/sub/'
[file] File size is 180297728 bytes
STREAM: [file] [AX] Kono Minikuku mo Utsukushii Sekai - 01 [71574CDB].avi
STREAM: Description: File
STREAM: Author: Albeu
STREAM: Comment: based on the code from ??? (probably Arpi)
LAVF_check: AVI (Audio Video Interleaved)
Detected file format: AVI (Audio Video Interleaved) (libavformat)
==> Found video stream: 0
======= VIDEO Format ======
  biSize 101
  biWidth 704
  biHeight 396
  biPlanes 0
  biBitCount 12
  biCompression 1446269005='MP4V'
  biSizeImage 418176
Unknown extra header dump: [0] [0] [1] [b0] [f5] [0] [0] [1] [b5] [9] [0] [0] [1] [0] [0] [0] [1] [20] [8] [ca] [d] [f] [ff] [fe] [15] [5b] [16] [4] [31] [94] [38] [3f] [0] [0] [1] [b2] [44] [69] [76] [58] [39] [39] [39] [62] [30] [30] [30] [70] [0] [0] [1] [b2] [58] [76] [69] [44] [30] [30] [33] [34] [43] 
===========================
[lavf] stream 0: video (mpeg4), -vid 0
==> Found audio stream: 1
======= WAVE Format =======
Format Tag: 85 (0x55)
Channels: 2
Samplerate: 48000
avg byte/sec: 16000
Block align: 384
bits/sample: 0
cbSize: 12
mp3.wID=1
mp3.fdwFlags=0x2
mp3.nBlockSize=384
mp3.nFramesPerBlock=1
mp3.nCodecDelay=0
==========================================================================
[lavf] stream 1: audio (mp3), -aid 0
LAVF: 1 audio and 1 video streams found
[ass] Raster: FreeType 2.13.2
[ass] Shaper: FriBidi 1.0.13 (SIMPLE) HarfBuzz-ng 8.4.0 (COMPLEX)
[ass] Initialized
get_path('fonts') -> '/home/sl1pkn07/.mplayer/fonts'
get_path('subfont.ttf') -> '/home/sl1pkn07/.mplayer/subfont.ttf'
[ass] Updating font cache
[V] filefmt:41  fourcc:0x5634504D  size:704x396  fps:23.976  ftime:=0.0417
Clip info:
 encoder: VirtualDubMod 1.5.10.1 (build 2439/release)
Load subtitles in .
get_path('sub/') -> '/home/sl1pkn07/.mplayer/sub/'
X11 opening display: :0
vo: X11 running at 3840x2160 with depth 24 (":0" => local display)
[x11] Detected wm supports NetWM.
[x11] Detected wm supports FULLSCREEN state.
[x11] Detected wm supports ABOVE state.
[x11] Detected wm supports STAYS_ON_TOP state.
[x11] Detected wm supports BELOW state.
[x11] Current fstype setting honours FULLSCREEN STAYS_ON_TOP ABOVE BELOW X atoms
[gl] GLX chose visual with ID 0x2f4
[gl] Detected OpenGL 4.6.
[gl] Detected OpenGL features: [Basic OpenGL] [Legacy OpenGL] [OpenGL 2.0] [OpenGL 2.1] [OpenGL 3.0] [Framebuffers] [VAOs] [sRGB textures] [sRGB framebuffers] [Float textures] [RG textures] [NO_SW]
[gl] Running on OpenGL 'NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2' by 'NVIDIA Corporation', version '4.6.0 NVIDIA 550.67'
[gl] Settings after autodetection: ati-hack = 0, force-pbo = 0, rectangle = 0, yuv = 2
vo: uninit ...
X11 opening display: :0
vo: X11 running at 3840x2160 with depth 24 (":0" => local display)
[x11] Detected wm supports NetWM.
[x11] Detected wm supports FULLSCREEN state.
[x11] Detected wm supports ABOVE state.
[x11] Detected wm supports STAYS_ON_TOP state.
[x11] Detected wm supports BELOW state.
[x11] Current fstype setting honours FULLSCREEN STAYS_ON_TOP ABOVE BELOW X atoms
[gl] using extended formats. Use -vo gl:nomanyfmts if playback fails.
[gl] Using 0 as slice height (0 means image height).
[vo] query(Planar YV12) -> 64b7
[ass] vf_ass not needed
Opening video decoder: [ffmpeg] libavcodec video codecs
Asking decoder to use 16 threads if supported.
Selected video codec: MPEG-4 part 2 [libavcodec]
Video codecs.conf entry: ffodivx (FFmpeg MPEG-4)  vfm: ffmpeg
Opening audio decoder: [mpg123] MPEG 1.0/2.0/2.5 layers I, II, III
dec_audio: Allocating 8192 + 65536 = 73728 bytes for output buffer.
MPEG 1.0 layer III, 128 kbit/s, 48000 Hz joint-stereo
Selected audio codec: MPEG 1.0/2.0/2.5 layers I, II, III [mpg123]
Audio codecs.conf entry: mpg123 (MPEG 1.0/2.0/2.5 layers I, II, III)  afm: mpg123
AUDIO: 48000 Hz, 2 ch, s16le, 128.0 kbit/8.33% (ratio: 16000->192000)
Building audio filter chain for 48000Hz/2ch/s16le -> 0Hz/0ch/??...
[libaf] Adding filter dummy 
[dummy] Was reinitialized: 48000Hz/2ch/s16le
Audio filter chain:
  [in] 48000Hz/2ch/s16le
  [dummy] 48000Hz/2ch/s16le
  [out] 0Hz/0ch/??
[dummy] Was reinitialized: 48000Hz/2ch/s16le
Audio filter chain:
  [in] 48000Hz/2ch/s16le
  [dummy] 48000Hz/2ch/s16le
  [out] 0Hz/0ch/??
Trying preferred audio driver 'pulse', options '[none]'
AO: [pulse] 48000Hz 2ch s16le (2 bytes per sample)
AO: Description: PulseAudio audio output
AO: Author: Lennart Poettering
Building audio filter chain for 48000Hz/2ch/s16le -> 48000Hz/2ch/s16le...
[dummy] Was reinitialized: 48000Hz/2ch/s16le
Audio filter chain:
  [in] 48000Hz/2ch/s16le
  [dummy] 48000Hz/2ch/s16le
  [out] 48000Hz/2ch/s16le
[dummy] Was reinitialized: 48000Hz/2ch/s16le
Audio filter chain:
  [in] 48000Hz/2ch/s16le
  [dummy] 48000Hz/2ch/s16le
  [out] 48000Hz/2ch/s16le
Starting playback...
[mpeg4 @ 0x56ad5914a820]Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter without encoding but stream copy to fix it.
[ffmpeg] aspect_ratio: 1.777778
VIDEO:  704x396  23.976 fps  857.6 kbps (107.2 kB/s)
VDec: vo config request - 704 x 396 (preferred colorspace: Planar YV12)
Trying filter chain: vo
Could not find matching colorspace - retrying with -vf scale...
Opening video filter: [scale]
SwScale params: -1 x -1 (-1=no scaling)
Trying filter chain: scale vo
The selected video_out device is incompatible with this codec.
Try appending the scale filter to your filter list,
e.g. -vf spp,scale instead of -vf spp.

FATAL: Could not initialize video filters (-vf) or video output (-vo).
EOF code: 2  

Uninit audio filters...
[libaf] Removing filter dummy 
Uninit audio: mpg123
Uninit video: ffmpeg
vo: uninit ...

Exiting... (End of file)
```
(add verbose)

is all over? :(

**Comment by astiob** [comment]
That’s… weird. It seems to be saying the vo doesn’t support planar YV12 and vf_scale can’t fix it. What if you try specifying an explicit `-vf scale,format=rgb24` or similar? `-vo gl3` certainly should handle YV12 natively, though; that’s what I used myself. I’m afraid I don’t have any other suggestions off the top of my head, and trying to debug this probably isn’t worth the time.

I’m not entirely sure what your end goal is, but have you tried MPlayer proper? You could also try `git bisect`ing this repo or mpv to find an older version that does what you want. But if it’s related to MPlayer’s heartbeat functionality, I don’t remember hearing much about it when mplayer2 development was still active, so I suspect it isn’t much different from MPlayer’s.

**Comment by sl1pkn07** [comment]
with heartbeat i mean make mplayer 2 works again, because stop working some time ago without any notice (i use mpv myself, but use mplayer for Qt4 apps notifications in kde with phonon-qt4-mplayer (https://invent.kde.org/unmaintained/phonon-mplayer and other certain apps use mplayer as backend)

i have use this repo https://repo.or.cz/mplayer2-build.git and https://repo.or.cz/mplayer2.git (and libav in https://repo.or.cz/FFMpeg-mirror/mplayer-patches.git) since long time without aparently problem, until notice the stop. 

I was hoping that if I compiled it with a "newer" ffmpeg with your fork it would be solved, but I see that it hasn't come back to life :(

maybe is because i'm on wayland? pass DISPLAY=:0 also do nothing. i'm out of ideas like you :S 

greetings

**Comment by sl1pkn07** [comment]
tested with ffplay 2.8.22. is not a problem with ffmpeg iself, so something is broken with mplayer2

**Comment by sl1pkn07** [comment]
horai!!!!!

![Screenshot_20240416_012743](https://github.com/astiob/mplayer2/assets/462213/40f82fee-9127-4f95-b89d-5f00c7c683be)

vdpau seems still working

vc=ffodivxvdpau,ffmpeg12vdpau,ffwmv3vdpa,ffvc1vdpau,ffh264vdpau,
vo=vdpau,

less is nothing

things like Hi10P or other newer features is not tested
